#!/bin/bash
echo 'post success'

head=$1
publish=$2
debug=$3
commitMsg=$4
tester=$5
developer=$6
googleKey=$7
packageName=$8

path=$(find . -type f -name '*.apk')

if $($debug); then
    type=debug
else
    type=release
fi

dir=$APK_DIR/$JOB_NAME/$type/$head
name=$(uuidgen)
# web取apk目录为/Users/addcn/pack/build/app
url=/app/$JOB_NAME/$type/$head/$name.apk
json=$dir/json/$name.json

mkdir -p $dir
mkdir -p $dir/json
mv $path $dir/$name.apk

if [ -e $json ]; then
    > $json
fi

time=$(date +'%Y-%m-%d %H:%M:%S')
commitId=$(git log -1 --format=%h)
echo "{\"icon\":\"/app/$JOB_NAME/icon.png\",\"name\":\"$JOB_NAME\",\"version\":\"$head\",\"date\":\"$time\",\"git_sha1\":\"$commitId\",\"download_url\":\"$url\",\"env\":\"$type\",\"description\":\"$commitMsg\"}" > $json

if $($publish); then
    $ACIS_HOME/upload $dir/$name.apk $googleKey $packageName $head
else
    msg="$commitMsg%0Ahttps://dl.8891.app"
    $ACIS_HOME/send $tester $msg
    $ACIS_HOME/send $developer "$head%20build%20success"
fi
